# Generated by Django 6.0.6 on 2026-08-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='labor_cost_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Labor charge in pesos (e.g. contractor billing amount).', max_digits=12, null=True),
        ),
    ]
