# Generated by Django 6.0.6 on 2026-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0002_joborder_labor_cost_pesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='labor_amount_paid_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid so far (partial releases).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='joborder',
            name='labor_payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='labor_cost_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total labor charge in pesos (contractor billing amount).', max_digits=12, null=True),
        ),
    ]
