# Generated by Django 6.0.6 on 2026-08-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0003_joborder_labor_amount_paid_pesos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='labor_amount_requested_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount requested for partial release.', max_digits=12, null=True, verbose_name='Amount Requested'),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='labor_amount_paid_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually paid/released so far.', max_digits=12, null=True, verbose_name='Amount Paid'),
        ),
    ]
