# Generated by Django 5.2.6 on 2026-07-24 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0003_truck_cr_expiry_truck_dost_calibration_expiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_expiry', models.DateField()),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage_km', models.IntegerField(default=0, help_text='End-of-day odometer reading')),
                ('engine_hours', models.DecimalField(decimal_places=1, default=0, help_text='End-of-day engine hours', max_digits=10)),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel added (liters)', max_digits=10, null=True)),
                ('idle_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('idle_count', models.IntegerField(default=0)),
                ('operating_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_traveled_km', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('max_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('avg_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('harsh_braking_count', models.IntegerField(default=0)),
                ('harsh_acceleration_count', models.IntegerField(default=0)),
                ('harsh_turning_count', models.IntegerField(default=0)),
                ('data_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CARTRACK', 'Cartrack API'), ('BOTH', 'Both')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trucks.truck')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='fleetops.driver')),
            ],
            options={
                'ordering': ['-date', 'truck__unit_number'],
                'unique_together': {('truck', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField()),
                ('assigned_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleetops.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='trucks.truck')),
            ],
            options={
                'ordering': ['-assigned_from'],
                'unique_together': {('driver', 'truck', 'assigned_from')},
            },
        ),
    ]
