# Generated by Django 6.0.6 on 2026-07-25 07:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetops', '0001_initial'),
        ('trucks', '0003_truck_cr_expiry_truck_dost_calibration_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CARTRACK', 'Cartrack'), ('TRACKSOLID', 'TrackSolid')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('heading', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('recorded_at', models.DateTimeField()),
                ('ignition_on', models.BooleanField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trucks.truck')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['truck', '-recorded_at'], name='fleetops_ve_truck_i_6b6326_idx')],
            },
        ),
    ]
