# Generated by Django 6.0.6 on 2026-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetops', '0002_vehicleposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleposition',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name='vehicleposition',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
