# Generated by Django 6.0.6 on 2026-08-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetops', '0002_alter_dailylog_engine_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='speeding_count',
            field=models.IntegerField(default=0),
        ),
    ]
