# Generated by Django 5.2.6 on 2026-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50, unique=True)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('tank_capacity_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DOWN', 'Down'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('current_mileage_km', models.IntegerField(default=0, help_text='Current odometer reading in km')),
                ('current_engine_hours', models.DecimalField(decimal_places=1, default=0, help_text='Current engine hours', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['unit_number'],
            },
        ),
    ]
