# Generated by Django 6.0.6 on 2026-07-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='body_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Body No.'),
        ),
        migrations.AddField(
            model_name='truck',
            name='body_type',
            field=models.CharField(blank=True, help_text='e.g. TANKER, WING VAN, DUMP TRUCK', max_length=100),
        ),
        migrations.AddField(
            model_name='truck',
            name='cr_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='CR Number'),
        ),
        migrations.AddField(
            model_name='truck',
            name='denomination',
            field=models.CharField(blank=True, help_text='e.g. TRUCK, TRACTOR HEAD', max_length=50),
        ),
        migrations.AddField(
            model_name='truck',
            name='field_office_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='truck',
            name='gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Weight (kg)'),
        ),
        migrations.AddField(
            model_name='truck',
            name='lto_registered_address',
            field=models.TextField(blank=True, verbose_name='LTO Registered Address'),
        ),
        migrations.AddField(
            model_name='truck',
            name='mv_file_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='MV File No'),
        ),
        migrations.AddField(
            model_name='truck',
            name='net_capacity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Capacity (kg)'),
        ),
        migrations.AddField(
            model_name='truck',
            name='net_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Weight (kg)'),
        ),
        migrations.AddField(
            model_name='truck',
            name='no_of_cylinders',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of Cylinders'),
        ),
        migrations.AddField(
            model_name='truck',
            name='or_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='OR Expiry/Validity'),
        ),
        migrations.AddField(
            model_name='truck',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='OR Number'),
        ),
        migrations.AddField(
            model_name='truck',
            name='piston_displacement_cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Piston Displacement (cc)'),
        ),
        migrations.AddField(
            model_name='truck',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='truck',
            name='shipping_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Shipping Weight (kg)'),
        ),
    ]
