# Generated by Django 5.2.6 on 2026-07-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_truck_body_no_truck_body_type_truck_cr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='cr_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='CR Expiry/Validity'),
        ),
        migrations.AddField(
            model_name='truck',
            name='dost_calibration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='DoST Calibration Expiry'),
        ),
        migrations.AddField(
            model_name='truck',
            name='fire_conveyance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Fire Conveyance Expiry'),
        ),
    ]
