# Generated by Django 6.0.6 on 2026-07-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MECHANIC', 'Mechanic'), ('CONTRACTOR', 'Contractor'), ('TRAINEE', 'OJT / Trainee')], default='STAFF', max_length=20),
        ),
    ]
