# Generated by Django 5.2.6 on 2026-06-26 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('interval_type', models.CharField(choices=[('MILEAGE', 'Mileage (km)'), ('HOURS', 'Engine Hours'), ('CALENDAR', 'Calendar (days)'), ('VISUAL', 'Visual Inspection')], default='MILEAGE', max_length=20)),
                ('interval_value', models.IntegerField(blank=True, help_text='Interval value (km, hours, or days)', null=True)),
                ('requires_specialist', models.BooleanField(default=False)),
                ('specialist_trade', models.CharField(blank=True, help_text='e.g., Electrician, Welder, Machinist', max_length=100)),
                ('estimated_labor_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='pms.taskcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_mileage_km', models.IntegerField(blank=True, null=True)),
                ('last_engine_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='trucks.truck')),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pms.tasktemplate')),
            ],
            options={
                'ordering': ['truck', 'task_template__category', 'task_template__name'],
                'unique_together': {('truck', 'task_template')},
            },
        ),
    ]
