# Generated by Django 5.2.6 on 2026-08-01 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_add_steering_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pmschedule',
            name='last_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='last_completed_source',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('JOB_ORDER', 'Job Order'), ('AUTO_CLOSE', 'Auto-complete on close'), ('ADMIN', 'Admin edit')], max_length=20),
        ),
    ]
