# Generated by Django 5.2.6 on 2026-06-26 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joborders', '0001_initial'),
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('mileage_at', models.IntegerField(blank=True, null=True)),
                ('engine_hours_at', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='joborders.joborder')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='joborders.joborderlineitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_log_entries', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='trucks.truck')),
            ],
            options={
                'verbose_name_plural': 'Service Log Entries',
                'ordering': ['-performed_at'],
            },
        ),
    ]
