# Generated by Django 5.2.6 on 2026-07-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joborders', '0001_initial'),
        ('service_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogentry',
            name='job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='joborders.joborder'),
        ),
    ]
