# Generated by Django 5.2.6 on 2026-07-21 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0002_alter_service_log_job_order_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogentry',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
