# Generated by Django 5.2.6 on 2026-07-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_log', '0003_alter_performed_at_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLogPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='service_log.servicelogentry')),
            ],
        ),
    ]
